# `scope.py set` -- the writer that makes a per-engine posture reachable.
#
# WHY THIS EXISTS. Until 0.6.1 nothing could produce a scope.json with mixed
# engines. `place.py file` copied core/templates/scope.json byte-for-byte, and
# that template says all four engines observe; `./prism promote <module>` wrote
# all four to enforce; `promote --all` deleted the file. The format supported a
# mixed file, both readers resolved one correctly, and no code could write one.
#
# The cost was measured on 2026-09-10. A project generated by `android create`
# has 17 findings before anybody writes a line -- so step 8b saw "findings" and
# copied the all-observe template, and a BRAND NEW repository installed with
# nothing blocking. Yet detekt and ktlint apply their baselines regardless of
# posture (DetektConventionPlugin sets `baseline` unconditionally and
# `ignoreFailures` separately), so those two could have enforced on day one with
# today's findings recorded and quiet. Only konsist (no baseline exists) and
# coverage (no measurement exists yet) actually had to observe.
#
# So the property under test is not "a file can be written". It is: SETTING ONE
# ENGINE MUST NOT DEMOTE THE OTHER THREE. An engine this file never names
# enforces, via load()'s ENFORCE_ALL seed -- which is what makes the shortest
# file the strictest one, and the opposite of copying a template.
# shellcheck disable=SC1091
. "$HOOK_DIR/tests/fixtures.sh"

SS_SCOPE="$HOOK_DIR/lib/scope.py"

ss_repo() {
    dir=$(mktemp -d)
    mkdir -p "$dir/.prism"
    printf 'include(":app")\ninclude(":core:domain")\n' > "$dir/settings.gradle.kts"
    printf '%s' "$dir"
}

# resolved posture for one module x engine, straight through the reader
ss_get() { "$PRISM_PY" "$SS_SCOPE" get --root "$1" --module "$2" --engine "$3" 2>&1; }

# --- 1. an absent file: one engine set, the other three still BLOCK --------
#
# This is the regression. 0.6.0's only way to reach this state placed a template
# in which all four observed.

ss1=$(ss_repo)
ss1_out=$("$PRISM_PY" "$SS_SCOPE" set --root "$ss1" --default \
    --engine konsist --posture observe 2>&1)

assert_contains "$ss1_out" "PLACED" \
    "set on a repository with no scope file places one"
assert_eq "observe" "$(ss_get "$ss1" ":app" konsist)" \
    "the engine that was named observes"
assert_eq "enforce" "$(ss_get "$ss1" ":app" detekt)" \
    "detekt STILL ENFORCES -- it was not named"
assert_eq "enforce" "$(ss_get "$ss1" ":app" ktlint)" \
    "ktlint STILL ENFORCES -- it was not named"
assert_eq "enforce" "$(ss_get "$ss1" ":app" coverage)" \
    "coverage STILL ENFORCES -- it was not named"
assert_contains "$ss1_out" "every engine it does not name enforces" \
    "and the output says so, because an installer has to report it"

# The file it wrote must be loadable by the reader that gates the build.
assert_contains "$("$PRISM_PY" "$SS_SCOPE" show --root "$ss1" 2>&1)" ":core:domain" \
    "the written file parses and resolves for every declared module"

# --- 2. idempotent, and it says which of the three things happened ---------

ss1_again=$("$PRISM_PY" "$SS_SCOPE" set --root "$ss1" --default \
    --engine konsist --posture observe 2>&1)
assert_contains "$ss1_again" "UNCHANGED" \
    "setting the same posture twice reports UNCHANGED"

ss1_second=$("$PRISM_PY" "$SS_SCOPE" set --root "$ss1" --default \
    --engine coverage --posture observe 2>&1)
assert_contains "$ss1_second" "UPDATED" \
    "a second engine on an existing file reports UPDATED"
assert_contains "$ss1_second" "enforce (unnamed)" \
    "and names what it was before, which for an unnamed engine is enforce"
assert_eq "enforce" "$(ss_get "$ss1" ":app" detekt)" \
    "two engines observing still leaves detekt blocking"

# --- 3. a module entry is a partial override, not a replacement ------------

ss1_mod=$("$PRISM_PY" "$SS_SCOPE" set --root "$ss1" --module :core:domain \
    --engine detekt --posture observe 2>&1)
assert_contains "$ss1_mod" "UPDATED" "a module override is written"
assert_eq "observe" "$(ss_get "$ss1" ":core:domain" detekt)" \
    "the named module observes detekt"
assert_eq "enforce" "$(ss_get "$ss1" ":app" detekt)" \
    "and its sibling is untouched"

# --- 4. it refuses rather than guesses ------------------------------------

"$PRISM_PY" "$SS_SCOPE" set --root "$ss1" --default --module :app \
    --engine detekt --posture observe >/dev/null 2>&1
assert_eq "2" "$?" "naming both --default and --module is refused"

"$PRISM_PY" "$SS_SCOPE" set --root "$ss1" --engine detekt --posture observe \
    >/dev/null 2>&1
assert_eq "2" "$?" "naming neither is refused"

"$PRISM_PY" "$SS_SCOPE" set --root "$ss1" --default --engine detekt \
    >/dev/null 2>&1
assert_eq "2" "$?" "a missing --posture is refused"

"$PRISM_PY" "$SS_SCOPE" set --root "$ss1" --default --engine spellcheck \
    --posture observe >/dev/null 2>&1
assert_eq "2" "$?" "an engine PRISM does not have is refused"

# --- 5. atomic, and it leaves no half-written gate ------------------------

assert_eq "absent" \
    "$([ -e "$ss1/.prism/scope.json.tmp" ] && echo present || echo absent)" \
    "no .tmp survives a successful write"

# --- 6. a file it cannot parse is NOT overwritten -------------------------
#
# Fails closed on the same terms as load(): the one case where guessing is
# worst is a gate-configuring file nobody can read.

ss2=$(ss_repo)
printf '{ this is not json' > "$ss2/.prism/scope.json"
ss2_out=$("$PRISM_PY" "$SS_SCOPE" set --root "$ss2" --default \
    --engine konsist --posture observe 2>&1); ss2_code=$?
assert_ne "0" "$ss2_code" "an unparseable scope file makes set refuse"
assert_contains "$ss2_out" "cannot be read" "and say why"
assert_eq "{ this is not json" "$(cat "$ss2/.prism/scope.json")" \
    "leaving the consumer's file exactly as it was"

# --- 7. a consumer's own $comment survives ------------------------------

ss3=$(ss_repo)
"$PRISM_PY" - "$ss3/.prism/scope.json" <<'PY'
import json, sys
json.dump({"$comment": ["ours", "keep this"],
           "default": {"detekt": "observe"}, "modules": {}},
          open(sys.argv[1], "w"), indent=2)
PY
"$PRISM_PY" "$SS_SCOPE" set --root "$ss3" --default --engine konsist \
    --posture observe >/dev/null 2>&1
assert_eq "ours keep this" "$("$PRISM_PY" -c '
import json,sys; print(" ".join(json.load(open(sys.argv[1]))["$comment"]))
' "$ss3/.prism/scope.json")" \
    "an existing \$comment is preserved rather than replaced"
assert_eq "observe" "$(ss_get "$ss3" ":app" detekt)" \
    "and the postures already in the file are preserved too"

# --- 8. `init` -- step 8b's write, in one idempotent call ------------------
#
# Separate from `set` because the install must not be a sequence of writes. A
# per-engine derivation built from four `set` calls has three intermediate
# states, and the second run of it would edit a consumer's promoted file.

ss4=$(ss_repo)

# A clean repository writes NO FILE. Absence is how enforce is installed, and an
# all-enforce file would be one the guard then refuses to let anyone delete.
ss4_clean=$("$PRISM_PY" "$SS_SCOPE" init --root "$ss4" 2>&1)
assert_contains "$ss4_clean" "NONE" "a clean repository has no scope file written"
assert_eq "absent" \
    "$([ -e "$ss4/.prism/scope.json" ] && echo present || echo absent)" \
    "and the file really is absent, which IS enforce"
assert_eq "enforce" "$(ss_get "$ss4" ":app" detekt)" \
    "so every engine enforces"

# The greenfield shape measured on 2026-09-10: detekt and ktlint can baseline
# what they found, konsist has no baseline and coverage has no measurement.
ss5=$(ss_repo)
ss5_out=$("$PRISM_PY" "$SS_SCOPE" init --root "$ss5" --observe konsist,coverage 2>&1)
assert_contains "$ss5_out" "PLACED" "engines that cannot enforce get a file"
assert_contains "$ss5_out" "enforce: detekt ktlint" \
    "and the output names what still blocks, not just what does not"
assert_eq "enforce" "$(ss_get "$ss5" ":app" detekt)" \
    "detekt ENFORCES on a brand-new install -- the 0.6.1 property"
assert_eq "enforce" "$(ss_get "$ss5" ":app" ktlint)" "ktlint enforces too"
assert_eq "observe" "$(ss_get "$ss5" ":app" konsist)" \
    "konsist observes, because no baseline exists for it"
assert_eq "observe" "$(ss_get "$ss5" ":app" coverage)" \
    "coverage observes, because no measurement exists yet"

# THE PHASE-2 PROPERTY, on the new writer. A second install must not undo a
# promotion, and this is the call that would have done it.
"$PRISM_PY" "$SS_SCOPE" set --root "$ss5" --module :core:domain \
    --engine konsist --posture enforce >/dev/null 2>&1
ss5_again=$("$PRISM_PY" "$SS_SCOPE" init --root "$ss5" --observe konsist,coverage 2>&1)
assert_contains "$ss5_again" "KEPT" "a second install keeps the consumer's file"
assert_eq "enforce" "$(ss_get "$ss5" ":core:domain" konsist)" \
    "THE PROMOTION SURVIVES the second install"

# A typo'd engine is refused even on a re-install, where nobody looks closely.
"$PRISM_PY" "$SS_SCOPE" init --root "$ss5" --observe konsist,spellcheck >/dev/null 2>&1
assert_eq "2" "$?" "an engine PRISM does not have is refused before KEPT is reported"

prism_fixture_cleanup "$ss1"
prism_fixture_cleanup "$ss2"
prism_fixture_cleanup "$ss3"
prism_fixture_cleanup "$ss4"
prism_fixture_cleanup "$ss5"
